#ifndef CONNACK_REASON_CODE_H
#define CONNACK_REASON_CODE_H

/**
 * The CONNACK reason codes.
 */
typedef enum {
  CONNACK_SUCCESS = 0x00,
  CONNACK_UNSPECIFIED_ERROR = 0x80,
  CONNACK_MALFORMED_PACKET = 0x81,
  CONNACK_PROTOCOL_ERROR = 0x82,
  CONNACK_IMPLEMENTATION_SPECIFIC_ERROR = 0x83,
  CONNACK_UNSUPPORTED_PROTOCOL_VERSION = 0x84,
  CONNACK_CLIENT_IDENTIFIER_NOT_VALID = 0x85,
  CONNACK_BAD_USER_NAME_OR_PASSWORD = 0x86,
  CONNACK_NOT_AUTHORIZED = 0x87,
  CONNACK_SERVER_UNAVAILABLE = 0x88,
  CONNACK_SERVER_BUSY = 0x89,
  CONNACK_BANNED = 0x8A,
  CONNACK_SERVER_SHUTTING_DOWN = 0x8B,
  CONNACK_BAD_AUTHENTICATION_METHOD = 0x8C,
  CONNACK_TOPIC_NAME_INVALID = 0x90,
  CONNACK_PACKET_TOO_LARGE = 0x95,
  CONNACK_QUOTA_EXCEEDED = 0x97,
  CONNACK_PAYLOAD_FORMAT_INVALID = 0x99,
  CONNACK_RETAIN_NOT_SUPPORTED = 0x9A,
  CONNACK_QOS_NOT_SUPPORTED = 0x9B,
  CONNACK_USE_ANOTHER_SERVER = 0x9C,
  CONNACK_SERVER_MOVED = 0x9D,
  CONNAK_CONNECTION_RATE_EXCEEDED = 0x9F
} connack_reason_code_t;

char *connack_reason_code_to_string(connack_reason_code_t reason_code);

#endif // CONNACK_REASON_CODE_H
